name: JSR Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate node_modules
        run: |
          npm i
          git checkout -- ./package-lock.json
      
      - name: Publish package
        run: npx jsr publish --allow-slow-types
